### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by usr-sse2** [zxystd/VirtualMac80211#1]
Are you trying to reimplement IO80211 integration from scratch instead of taking and improving an already working implementation? I think that collaboration is more efficient than competition and wanted to make a PR to OpenIntelWireless/itlwm after fixing some critical issues with scanning and association status.

**Comment by zxystd** [comment]
very appreciate your work, it is just a funny research that use wifi interface without using IO80211Family, fake as IO80211Family and do what it was do. not related about itlwm. :)
